### PR TITLE
update to 1.18

### PR DESCRIPTION
**Pull request by plusls**

### CODE REVIEW

**Comment by plusls** [comment]
学业繁忙，低版本未测

**Review by Kichura — COMMENTED** [review]
Github actions must be changed to JDK 17 as mojang changed their engine to that version,

Otherwise this looks pretty good so far.

**Comment by mrjesen** [comment]
> Github actions must be changed to JDK 17 as mojang changed their engine to that version,
> 
> Otherwise this looks pretty good so far.

but,in the lower version it does't need jdk17... and in my opinion, "one file fixes all versions" is best.

**Review by Kichura — APPROVED** [review]
Compiles properly now - good job.

**Comment by mrjesen** [comment]
测了一下，1.14.4，1.15.2好像不太行，可能我这里环境有点问题。 我一会重新测一下。

**Comment by mrjesen** [comment]
麻烦看一下1.14.4和1.15.2，实锤失效

**Comment by plusls** [comment]
我测了一下 1.15.2 能用呀

**Comment by mrjesen** [comment]
> 我测了一下 1.15.2 能用呀

我去？奇了怪了。

**Comment by mrjesen** [comment]
先合并再说，但是1.14我确实是不能运行

**Comment by plusls** [comment]
> 先合并再说，但是1.14我确实是不能运行

我刚才测了一下1.14没问题啊

**Comment by mrjesen** [comment]
> > 先合并再说，但是1.14我确实是不能运行
> 
> 我刚才测了一下1.14没问题啊

尴尬啊，那我再试试

**Pull request merged**
